apiVersion: apps/v1
kind: Deployment
metadata:
  name: parcial-aks-deployment
  labels:
    app: parcial-aks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parcial-aks
  template:
    metadata:
      labels:
        app: parcial-aks
    spec:
      containers:
      - name: parcial-aks
        image: fabioramos97/xampp-parcial-k8s
        ports:
        - containerPort: 22
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www
          name: webapp-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: webapp-claim0
        persistentVolumeClaim:
          claimName: webapp-claim0